### ISSUE TITLE
OSX Font Issue

### ISSUE THREAD

**Issue by louy** [forabi/aQuran#3]
There's an issue in OSX that makes Arabic words break on multiple lines.
Changing css white-space will fix this.

![aquran](https://cloud.githubusercontent.com/assets/349850/2673369/eae0500a-c0f2-11e3-9788-734661afc04e.png)

**Comment by louy** [comment]
Also note the Ayah sign issue, afaik there's no solution but to place the character and the number above each other. I'll try to make a patch for this.

**Comment by louy** [comment]
Anyway I had the same issue in Aliqtisadi Prayer page (http://aliqtisadi.com/prayer/).
I used an image there to solve this and placed hidden parenthesis "{}" that will appear when the user copies the text :)

**Comment by forabi** [comment]
I will open a separate issue for the aya sign.
