### ISSUE TITLE
preference menu bug

### ISSUE THREAD

**Issue by Ak-0** [forabi/aQuran#7]
Font background changes when entering any option from preferences. ZTE open C FFOS 1.3.
![blob](https://cloud.githubusercontent.com/assets/8528895/4019688/ce273b42-2a81-11e4-8b86-c8353339d621.png)

**Comment by forabi** [comment]
Thanks for taking time to report this, this version is no longer maintained. I'm in the process of rewriting major parts of the app with focus on performance and localization. If you have other issues or suggestions, please let me know.

**Comment by Ak-0** [comment]
It's a great app in actualiza
