### ISSUE TITLE
Allow Mouse Scrolling for none touch computer

### ISSUE THREAD

**Issue by zaher** [forabi/aQuran#8]
Allow Mouse Scrolling wheel for none touch computer, PC if we used it from normal browsers

**Comment by forabi** [comment]
This project is no longer maintained. It needs a full rewrite. Angular 1.x does not perform well on mobile devices. If I had time to rewrite, I'd go with TypeScript + Preact (_not_ React) + Redux. A good starting point would be to check out the current work on https://github.com/forabi/WebCeph2. It is set up with the exact same technology stack (TS, Preact, Redux, Webpack) and enforces strict performance and compatibility requirements with CI and cross-browser tests.
